stages:
  - test-editmode
  - test-playmode
  - build-windows
  - build-linux

variables:
  BUILD_NAME: SzenvedIK
  IMAGE: unityci/editor # https://hub.docker.com/r/unityci/editor
  IMAGE_VERSION: "3"
  UNITY_DIR: $CI_PROJECT_DIR
  UNITY_VERSION: "6000.0.38f1"
  VERSION_NUMBER_VAR: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_JOB_ID
  VERSION_BUILD_VAR: $CI_PIPELINE_IID

image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

.unity_before_script: &unity_before_script
  before_script:
    - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

.unity_after_script: &unity_after_script
  after_script:
    - chmod +x ./ci/return_license.sh && ./ci/return_license.sh

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - $UNITY_DIR/Library/
      - $UNITY_DIR/../unity-builder

.license: &license
  rules:
    - if: '$UNITY_LICENSE != null || $UNITY_SERIAL != null'
      when: always

.unity_defaults: &unity_defaults
  <<:
    - *unity_before_script
    - *cache
    - *license
    - *unity_after_script

.test: &test
  <<: *unity_defaults
  script:
    - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    when: always
    expire_in: 2 weeks
  coverage: /<Linecoverage>(.*?)</Linecoverage>/

test-editmode:
  <<: *test
  stage: test-editmode
  variables:
    TEST_PLATFORM: editmode
    TESTING_TYPE: NUNIT

test-playmode:
  <<: *test
  stage: test-playmode
  needs:
    - job: test-editmode
  variables:
    TEST_PLATFORM: playmode
    TESTING_TYPE: NUNIT

.build: &build
  <<: *unity_defaults
  script:
    - chmod +x ./ci/build.sh && ./ci/build.sh
  artifacts:
    paths:
      - $UNITY_DIR/Builds/

build-StandaloneWindows64:
  <<: *build
  stage: build-windows
  needs:
    - job: test-playmode
  image: $IMAGE:$UNITY_VERSION-windows-mono-$IMAGE_VERSION
  variables:
    BUILD_TARGET: StandaloneWindows64

build-StandaloneLinux64:
  <<: *build
  stage: build-linux
  needs:
    - job: build-StandaloneWindows64
  variables:
    BUILD_TARGET: StandaloneLinux64

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
